### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by bkowshik** [willemarcel/osmcha#11]
Found the following error log during my local run of `osmcha-django`

- Changeset: http://www.openstreetmap.org/api/0.6/changeset/34493733/download

### from osmchadjango.changeset.tasks import import_replications

```sh
[2017-02-09 06:56:55,923: WARNING/Worker-2] # changeset
[2017-02-09 06:56:55,923: WARNING/Worker-2] 34493733
[2017-02-09 06:56:55,924: WARNING/Worker-2] # Downloading...
[2017-02-09 06:56:55,924: WARNING/Worker-2] http://www.openstreetmap.org/api/0.6/changeset/34493733/download
[2017-02-09 06:56:56,338: WARNING/Worker-3] # xml
[2017-02-09 06:56:56,339: WARNING/Worker-3] <Element 'osmChange' at 0x106bb6f90>
[2017-02-09 06:56:56,341: ERROR/MainProcess] Task osmchadjango.changeset.tasks.create_changeset[b0da0874-651a-4993-bd4c-729510425b70] raised unexpected: ZeroDivisionError('integer division or modulo by zero',)
Traceback (most recent call last):
  File "/Users/demo/.virtualenvs/osmcha-django/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/demo/.virtualenvs/osmcha-django/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/demo/repos/batpad/osmcha-django/osmchadjango/changeset/tasks.py", line 20, in create_changeset
    ch.full_analysis()
  File "/Users/demo/.virtualenvs/osmcha-django/lib/python2.7/site-packages/osmcha/changeset.py", line 200, in full_analysis
    self.count()
  File "/Users/demo/.virtualenvs/osmcha-django/lib/python2.7/site-packages/osmcha/changeset.py", line 348, in count
    if self.create / len(actions) > 0.7 and \
ZeroDivisionError: integer division or modulo by zero
[2017-02-09 06:56:56,344: INFO/MainProcess] Received task: osmchadjango.changeset.tasks.create_changeset[cd33587d-5cc9-4a38-86e0-5b20d5181b02]
[2017-02-09 06:56:56,350: WARNING/Worker-2] # xml
[2017-02-09 06:56:56,350: WARNING/Worker-2] <Element 'osmChange' at 0x101e9f4d0>
[2017-02-09 06:56:56,363: WARNING/Worker-2] /Users/demo/.virtualenvs/osmcha-django/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Changeset.date received a naive datetime (2015-10-07 15:46:47) while time zone support is active.
  RuntimeWarning)
[2017-02-09 06:56:56,370: WARNING/Worker-2] 34493733 created
[2017-02-09 06:56:56,371: INFO/MainProcess] Task osmchadjango.changeset.tasks.create_changeset[09073c46-50a2-4056-94d7-7dc3d31ae1cf] succeeded in 0.811421988008s: None
```

### Command line run
```sh
$ osmcha 34493733
# changeset 34493733
# Downloading... http://www.openstreetmap.org/api/0.6/changeset/34493733/download
# xml <Element 'osmChange' at 0x111064fd0>
Created: 0. Modified: 1. Deleted: 0
The changeset 34493733 is not suspect!
```

---

cc: @willemarcel @batpad

**Comment by bkowshik** [comment]
Got another, posting here to aid debugging.

- Changeset: http://www.openstreetmap.org/api/0.6/changeset/34495147/download

```sh
[2017-02-09 07:06:16,756: WARNING/Worker-4] # changeset
[2017-02-09 07:06:16,757: WARNING/Worker-4] 34495147
[2017-02-09 07:06:16,757: WARNING/Worker-4] # Downloading...
[2017-02-09 07:06:16,757: WARNING/Worker-4] http://www.openstreetmap.org/api/0.6/changeset/34495147/download
[2017-02-09 07:06:17,128: WARNING/Worker-4] # xml
[2017-02-09 07:06:17,128: WARNING/Worker-4] <Element 'osmChange' at 0x106dd5810>
[2017-02-09 07:06:17,134: ERROR/MainProcess] Task osmchadjango.changeset.tasks.create_changeset[34f6b92a-73d8-4d61-9786-3be92109a57c] raised unexpected: ZeroDivisionError('integer division or modulo by zero',)
Traceback (most recent call last):
  File "/Users/demo/.virtualenvs/osmcha-django/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/demo/.virtualenvs/osmcha-django/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/demo/repos/batpad/osmcha-django/osmchadjango/changeset/tasks.py", line 20, in create_changeset
    ch.full_analysis()
  File "/Users/demo/.virtualenvs/osmcha-django/lib/python2.7/site-packages/osmcha/changeset.py", line 200, in full_analysis
    self.count()
  File "/Users/demo/.virtualenvs/osmcha-django/lib/python2.7/site-packages/osmcha/changeset.py", line 348, in count
    if self.create / len(actions) > 0.7 and \
ZeroDivisionError: integer division or modulo by zero
[2017-02-09 07:06:17,136: INFO/MainProcess] Received task: osmchadjango.changeset.tasks.create_changeset[03064cad-3a24-48d4-b828-e0cb93af3230]
```

**Comment by batpad** [comment]
Thanks much for the reports @bkowshik !

@willemarcel can you try and reproduce with these changeset ids, and we can see wht's going on here? My guess is for these changesets, `actions` is 0, for some reason?

**Comment by willemarcel** [comment]
@bkowshik fixed with https://github.com/willemarcel/osmcha/commit/966211d4be1481024b40a75538632dc2dac64d08

@batpad I believe the actions is 0 when the changeset is redacted. The DWG need to do this when ilegal data is included in OSM.

**Comment by bkowshik** [comment]
@willemarcel I don't understand what are `redacted` changesets. Where can I read more about `redacted` changesets? Let me know if you have links.

**Comment by willemarcel** [comment]
@bkowshik look at https://wiki.openstreetmap.org/wiki/Data_working_group#Redactions
